import { useApp } from '@/context/AppContext';
import { featuredRecipes } from '@/data';
import { tr } from '@/i18n';
import { Clock, Users, ChefHat } from 'lucide-react';

export default function FeaturedRecipes() {
  const { language } = useApp();

    return (
        <section id="featured" className="py-20 bg-tagine-50/30 dark:bg-zellige-950 transition-colors duration-300">
              <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
                      <div className="text-center max-w-3xl mx-auto mb-16">
                                <span className="text-saffron-600 dark:text-saffron-400 font-bold text-sm tracking-wider uppercase block mb-3">
                                            {tr('featuredEyebrow', language)}
                                                      </span>
                                                                <h2 className="text-3xl sm:text-4xl font-black text-zellige-900 dark:text-white mb-4">
                                                                            {tr('featuredTitle', language)}
                                                                                      </h2>
                                                                                                <p className="text-tagine-700 dark:text-tagine-300">
                                                                                                            {tr('featuredSubtitle', language)}
                                                                                                                      </p>
                                                                                                                              </div>

                                                                                                                                      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
                                                                                                                                                {featuredRecipes.map((recipe) => (
                                                                                                                                                            <div key={recipe.id} className="bg-white dark:bg-zellige-900 rounded-3xl overflow-hidden border border-tagine-200 dark:border-tagine-800 shadow-sm hover:shadow-xl transition-all duration-300 flex flex-col">
                                                                                                                                                                          <div className="relative h-56 overflow-hidden">
                                                                                                                                                                                          <img
                                                                                                                                                                                                            src={recipe.image}
                                                                                                                                                                                                                              alt={language === 'ar' ? recipe.name : recipe.nameEn}
                                                                                                                                                                                                                                                className="w-full h-full object-cover hover:scale-105 transition-transform duration-500"
                                                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                            <div className="p-6 flex-1 flex flex-col justify-between space-y-4">
                                                                                                                                                                                                                                                                                                            <div>
                                                                                                                                                                                                                                                                                                                              <h3 className="text-xl font-bold text-zellige-900 dark:text-white mb-2">
                                                                                                                                                                                                                                                                                                                                                  {language === 'ar' ? recipe.name : recipe.nameEn}
                                                                                                                                                                                                                                                                                                                                                                    </h3>
                                                                                                                                                                                                                                                                                                                                                                                      <p className="text-tagine-600 dark:text-tagine-400 text-sm line-clamp-2">
                                                                                                                                                                                                                                                                                                                                                                                                          {language === 'ar' ? recipe.description : recipe.descriptionEn}
                                                                                                                                                                                                                                                                                                                                                                                                                            </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="flex items-center justify-between text-xs text-tagine-500 dark:text-tagine-400 pt-4 border-t border-tagine-100 dark:border-tagine-800">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="flex items-center gap-1">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Clock className="w-4 h-4 text-saffron-500" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <span>{language === 'ar' ? recipe.cookTime : recipe.cookTimeEn}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="flex items-center gap-1">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Users className="w-4 h-4 text-terracotta-500" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span>{language === 'ar' ? recipe.servings : recipe.servingsEn}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="p-3 rounded-xl bg-tagine-50 dark:bg-zellige-950/50 border border-tagine-100 dark:border-tagine-900 text-xs text-tagine-700 dark:text-tagine-300 space-y-1">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="font-semibold flex items-center gap-1 text-saffron-600 dark:text-saffron-400">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <ChefHat className="w-3.5 h-3.5" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <span>{tr('chefTip', language)}:</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p>{language === 'ar' ? recipe.tip : recipe.tipEn}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
