import { useApp } from '@/context/AppContext';
import { tr } from '@/i18n';
import { BUY_URL } from '@/constants';
import { Globe, Moon, Sun, ShoppingBag } from 'lucide-react';

export default function Header() {
  const { theme, language, toggleTheme, toggleLanguage } = useApp();

    return (
        <header className="sticky top-0 z-50 bg-white/90 dark:bg-zellige-950/90 backdrop-blur-md border-b border-tagine-100 dark:border-tagine-900 transition-colors duration-300">
              <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-20 flex items-center justify-between">
                      <div className="flex items-center gap-3">
                                <div className="w-10 h-10 rounded-xl bg-gradient-to-tr from-saffron-500 to-terracotta-600 flex items-center justify-center text-white font-bold text-xl shadow-md">
                                            
                                                      </div>
                                                                <div>
                                                                            <span className="font-bold text-lg block text-zellige-900 dark:text-saffron-50">
                                                                                          {tr('brand', language)}
                                                                                                      </span>
                                                                                                                  <span className="text-xs text-tagine-600 dark:text-tagine-300 block">
                                                                                                                                {tr('brandTag', language)}
                                                                                                                                            </span>
                                                                                                                                                      </div>
                                                                                                                                                              </div>

                                                                                                                                                                      <nav className="hidden md:flex items-center gap-8">
                                                                                                                                                                                <a href="#about" className="text-sm font-medium text-zellige-800 dark:text-zellige-200 hover:text-saffron-600 transition-colors">
                                                                                                                                                                                            {tr('navAbout', language)}
                                                                                                                                                                                                      </a>
                                                                                                                                                                                                                <a href="#featured" className="text-sm font-medium text-zellige-800 dark:text-zellige-200 hover:text-saffron-600 transition-colors">
                                                                                                                                                                                                                            {tr('navFeatured', language)}
                                                                                                                                                                                                                                      </a>
                                                                                                                                                                                                                                              </nav>

                                                                                                                                                                                                                                                      <div className="flex items-center gap-3">
                                                                                                                                                                                                                                                                <button
                                                                                                                                                                                                                                                                            onClick={toggleLanguage}
                                                                                                                                                                                                                                                                                        className="p-2.5 rounded-xl border border-tagine-200 dark:border-tagine-800 text-zellige-800 dark:text-zellige-200 hover:bg-tagine-50 dark:hover:bg-tagine-900/50 transition-colors flex items-center gap-1.5 text-sm font-medium"
                                                                                                                                                                                                                                                                                                    title="Switch Language"
                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                          <Globe className="w-4 h-4 text-saffron-500" />
                                                                                                                                                                                                                                                                                                                                      <span>{tr('langToggle', language)}</span>
                                                                                                                                                                                                                                                                                                                                                </button>

                                                                                                                                                                                                                                                                                                                                                          <button
                                                                                                                                                                                                                                                                                                                                                                      onClick={toggleTheme}
                                                                                                                                                                                                                                                                                                                                                                                  className="p-2.5 rounded-xl border border-tagine-200 dark:border-tagine-800 text-zellige-800 dark:text-zellige-200 hover:bg-tagine-50 dark:hover:bg-tagine-900/50 transition-colors"
                                                                                                                                                                                                                                                                                                                                                                                              title="Toggle Theme"
                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                    {theme === 'light' ? <Moon className="w-4 h-4 text-zellige-700" /> : <Sun className="w-4 h-4 text-saffron-400" />}
                                                                                                                                                                                                                                                                                                                                                                                                                              </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                        <a
                                                                                                                                                                                                                                                                                                                                                                                                                                                    href={BUY_URL}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                target="_blank"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            rel="noopener noreferrer"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className="hidden sm:inline-flex items-center gap-2 px-5 py-2.5 rounded-xl bg-gradient-to-r from-saffron-500 to-terracotta-600 text-white font-medium text-sm shadow-lg shadow-saffron-500/20 hover:from-saffron-600 hover:to-terracotta-700 transition-all transform hover:-translate-y-0.5"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <ShoppingBag className="w-4 h-4" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <span>{tr('navBuy', language)}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </header>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
