import type { Category, FeaturedRecipe } from './types';

export const categories: Category[] = [
  {
    id: 'tagines',
    name: 'الطواجن', nameEn: 'Tagines',
    description: 'أطباق مطبوخة ببطء في أواني فخارية تقليدية',
    descriptionEn: 'Slow-cooked stews in traditional clay pots',
  },
  {
    id: 'couscous',
    name: 'الكسكس', nameEn: 'Couscous',
    description: 'الكسكس الخفيف بالخضار واللحوم',
    descriptionEn: 'Light couscous with vegetables and meats',
  },
  {
    id: 'soups',
    name: 'الشوربات', nameEn: 'Soups',
    description: 'حريرة وغيرها من الشوربات المغربية الغنية',
    descriptionEn: 'Harira and other rich Moroccan soups',
  },
  {
    id: 'salads',
    name: 'السلطات', nameEn: 'Salads',
    description: 'سلطات طازجة بالخضار الموسمية',
    descriptionEn: 'Fresh salads with seasonal vegetables',
  },
  {
    id: 'baked',
    name: 'المخبوزات', nameEn: 'Baked Goods',
    description: 'الخبز التقليدي والمخبوزات المغربية',
    descriptionEn: 'Traditional breads and Moroccan pastries',
  },
  {
    id: 'fish',
    name: 'السمك', nameEn: 'Fish',
    description: 'أطباق السمك بأسلوب المدن الساحلية',
    descriptionEn: 'Fish dishes in coastal-city style',
  },
  {
    id: 'desserts',
    name: 'الحلويات', nameEn: 'Desserts',
    description: 'حلويات مغربية أصيلة مثل الشباكية والسلو',
    descriptionEn: 'Authentic Moroccan sweets like Chebakia and Selou',
  },
];

export const featuredRecipes: FeaturedRecipe[] = [
  {
    id: 'chicken-tagine-olives',
    name: 'طاجين الدجاج بالزيتون والليمون المخلل',
    nameEn: 'Chicken Tagine with Olives & Preserved Lemons',
    description: 'دجاج طري مطبوخ ببطء مع زيتون أحمر وأخضر وليمون مخلل وبهارات تقليدية',
    descriptionEn: 'Tender chicken slow-cooked with red and green olives, preserved lemons, and traditional spices',
    prepTime: '٢٠ دقيقة', cookTime: 'ساعة و١٥ دقيقة', cookTimeEn: '1h 15m',
    servings: '٤ أشخاص', servingsEn: '4 servings',
    story: 'هذا الطبق رمز للضيافة المغربية، يُقدّم في المناسبات العائلية الكبيرة ويجمع بين نكهة الليمون المخلل الحاد وزيتون الوادي المملح.',
    storyEn: 'A symbol of Moroccan hospitality, served at large family gatherings, combining the sharpness of preserved lemons with valley olives.',
    tip: 'استخدم الليمون المخلل المصنوع في البيت (beldi) للحصول على النكهة الأصيلة، ولا تستخدم الزيتون المعلب.',
    tipEn: 'Use homemade preserved lemons (beldi) for authentic flavor; avoid canned olives.',
    image: 'https://images.pexels.com/photos/998244/pexels-photo-998244.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  },
  {
    id: 'seven-veg-couscous',
    name: 'كسكس السبع خضروات',
    nameEn: 'Seven-Vegetable Couscous',
    description: 'كسكس خفيف فوقه سبع أنواع من الخضار المطبوخة في مرق غني بالبهارات',
    descriptionEn: 'Light couscous topped with seven vegetables simmered in a rich spiced broth',
    prepTime: '٣٠ دقيقة', cookTime: 'ساعة', cookTimeEn: '1h',
    servings: '٦ أشخاص', servingsEn: '6 servings',
    story: 'يُقدّم كسكس السبع خضروات تقليدياً يوم الجمعة بعد الصلاة، وكل خضرة ترمز إلى البركة والوفرة في المنزل.',
    storyEn: 'Traditionally served on Fridays after prayer, each vegetable symbolizing blessing and abundance in the home.',
    tip: 'اهل الكسكس يدوياً (beldi) بدل الكسكس سريع التحضير، وافركه بزيت الزيتون البكر قبل البخار لمنع تكتله.',
    tipEn: 'Steam hand-rolled couscous (beldi) rather than instant, and rub with virgin olive oil before steaming to prevent clumping.',
    image: 'https://images.pexels.com/photos/29594950/pexels-photo-29594950.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  },
  {
    id: 'chicken-almond-bastilla',
    name: 'بسطيلة الدجاج باللوز',
    nameEn: 'Chicken & Almond Bastilla',
    description: 'طبق احتفالي يجمع بين الحلو والمالح: دجاج، لوز، قرفة، سكر، ورق الورقة',
    descriptionEn: 'A festive dish blending sweet and savory: chicken, almonds, cinnamon, sugar, and warqa pastry',
    prepTime: '٤٥ دقيقة', cookTime: 'ساعة و٣٠ دقيقة', cookTimeEn: '1h 30m',
    servings: '٨ أشخاص', servingsEn: '8 servings',
    story: 'البسطيلة طبق ملكي يُقدّم في الأعراس والمناسبات الكبرى، وأصلها من مدينة فاس العتيقة حيث تُعتبر قمة فن الطبخ المغربي.',
    storyEn: 'A royal dish served at weddings and major celebrations, originating from ancient Fez, considered the pinnacle of Moroccan culinary art.',
    tip: 'استخدم ورق الورقة الطازج وليس ورق الفيلو، واخلط الدجاج باللوز المحمص والمطحون لإعطاء قوام غني.',
    tipEn: 'Use fresh warqa pastry, not phyllo; mix chicken with toasted ground almonds for a rich texture.',
    image: 'https://images.pexels.com/photos/14017961/pexels-photo-14017961.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  },
  {
    id: 'harira-soup',
    name: 'حريرة المغربية',
    nameEn: 'Harira Soup',
    description: 'شوربة غنية بالحمص والعدس والطماطم واللحم والكزبرة والكرفس',
    descriptionEn: 'Rich soup with chickpeas, lentils, tomatoes, meat, coriander, and celery',
    prepTime: '١٥ دقيقة', cookTime: 'ساعة و١٠ دقيقة', cookTimeEn: '1h 10m',
    servings: '٦ أشخاص', servingsEn: '6 servings',
    story: 'حريرة طبق رمضان الأساسي، تُفطر عليه الأسر المغربية بعد صيام النهار، ورائحتها تملأ البيت بدفء العائلة.',
    storyEn: 'The essential Ramadan dish, breaking the fast in Moroccan homes, its aroma filling the house with family warmth.',
    tip: 'أضف خليط الطماطم المعجون (tadouira) في النهاية ليثقل قوام الحريرة، وزيّنها بالكزبرة الطازجة والتمر.',
    tipEn: 'Add the tomato concentrate mixture (tadouira) at the end to thicken the harira; garnish with fresh coriander and dates.',
    image: 'https://images.pexels.com/photos/2287528/pexels-photo-2287528.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  },
  {
    id: 'lamb-tagine-prunes',
    name: 'طاجين لحم الضأن بالبرقوق',
    nameEn: 'Lamb Tagine with Prunes',
    description: 'لحم ضأن طري مع برقوق مجفف، لوز محمص، قرفة، وعسل في صلصة حلوة مالحة',
    descriptionEn: 'Tender lamb with dried prunes, toasted almonds, cinnamon, and honey in a sweet-savory sauce',
    prepTime: '٢٠ دقيقة', cookTime: 'ساعتان', cookTimeEn: '2h',
    servings: '٦ أشخاص', servingsEn: '6 servings',
    story: 'من أرقى أطباق الطاجين المغربي، يُقدّم في الأعياد والولائم، ويجمع بين حلاوة البرقوق وعمق نكهة اللحم.',
    storyEn: 'One of the finest Moroccan tagines, served at Eid and feasts, marrying prune sweetness with deep lamb flavor.',
    tip: 'انقع البرقوق في الشاي الأخضر قبل الطهي لإعطاء نكهة عطرية فريدة، واستخدم لحم الكتف المقطّع كبيرة.',
    tipEn: 'Soak prunes in green tea before cooking for a unique aromatic note; use large-cut shoulder of lamb.',
    image: 'https://images.pexels.com/photos/30068444/pexels-photo-30068444.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  },
  {
    id: 'selou',
    name: 'السلو',
    nameEn: 'Selou',
    description: 'حلوى مغربية مغذية من الدقيق المحمص واللوز والسمسم والعسل والسمن beldi',
    descriptionEn: 'Nutritious Moroccan sweet of toasted flour, almonds, sesame, honey, and beldi ghee',
    prepTime: '٣٠ دقيقة', cookTime: '٤٥ دقيقة', cookTimeEn: '45m',
    servings: '١٠ أشخاص', servingsEn: '10 servings',
    story: 'السلو طبق رمضاني وعائلي بامتياز، يُحضّر بأيدي النساء في البيت، ويُقدّم مع الشاي بالنعناع في الصباح.',
    storyEn: 'A quintessentially Ramadan and family dish, prepared by hand at home, served with mint tea in the morning.',
    tip: 'حمّص الدقيق على نار هادئة جداً مع التحريك المستمر حتى يصير ذهبياً دون أن يحترق، واستخدم السمن beldi فقط.',
    tipEn: 'Toast flour on very low heat with constant stirring until golden without burning; use only beldi ghee.',
    image: 'https://images.pexels.com/photos/3889842/pexels-photo-3889842.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  },
  {
    id: 'chebakia',
    name: 'الشباكية',
    nameEn: 'Chebakia',
    description: 'حلوى مقلية على شكل وردة، مغموسة في العسل ومرشوشة بالسمسم',
    descriptionEn: 'Flower-shaped fried pastry soaked in honey and sprinkled with sesame',
    prepTime: '٤٠ دقيقة', cookTime: '٣٠ دقيقة', cookTimeEn: '30m',
    servings: '٢٠ قطعة', servingsEn: '20 pieces',
    story: 'الشباكية رفيقة الحريرة في رمضان، شكلها كالوردة وطعمها كالعسل، وتُحضّر بكميات كبيرة في آخر شعبان لتدوم الشهر كله.',
    storyEn: "Harira's companion in Ramadan, flower-shaped and honey-sweet, prepared in large batches at the end of Sha'ban to last the month.",
    tip: 'اعجن العجينة بماء الزهر (ماء الورد) لإعطاء عطر مميز، واقليها على نار متوسطة حتى تذهّب دون أن تتحمر كثيراً.',
    tipEn: 'Knead the dough with orange blossom water for a distinctive aroma; fry on medium heat until golden without over-browning.',
    image: 'https://images.pexels.com/photos/18077172/pexels-photo-18077172.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  },
  {
    id: 'mint-tea',
    name: 'أتاي بالنعناع',
    nameEn: 'Moroccan Mint Tea',
    description: 'الشاي الأخضر بالنعناع الطازج والسكر، يُقدّم في كؤوس مزخرفة',
    descriptionEn: 'Green tea with fresh mint and sugar, served in ornate glasses',
    prepTime: '٥ دقائق', cookTime: '١٥ دقيقة', cookTimeEn: '15m',
    servings: '٤ أكواب', servingsEn: '4 cups',
    story: 'أتاي رمز الكرم المغربي، تحضيره طقس اجتماعي، وسكبه من علو لإنتاج الرغوة فن يُقدّر في كل بيت.',
    storyEn: 'Atay is a symbol of Moroccan generosity; its preparation is a social ritual, and pouring from height to create foam is an art prized in every home.',
    tip: 'استخدم النعناع البلدي (beldi) ذا الأوراق الصغيرة، واغسله جيداً دون عصره، وأضف السكر حسب الذوق المغربي (كثير).',
    tipEn: 'Use beldi mint with small leaves, wash gently without crushing, and add sugar the Moroccan way (generously).',
    image: 'https://images.pexels.com/photos/30497987/pexels-photo-30497987.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  },
];
